### PR TITLE
Works around 'Forbidden (CSRF token missing...)

### PR DESCRIPTION
**Pull request by guillemlc**
Works around the "Forbidden (CSRF token missing or incorrect.): /"

With following combination:
MacOSX 10.11.6 (15G1421)
geckodriver 0.16.1
Python 3.6.1
FF version 53
selenium 3.4.1
Django 1.11

### CODE REVIEW

**Comment by hjwp** [comment]
Hi there, thanks for taking the time to submit a PR! But there shouldn't be any CSRF problems in the book.  Where are you seeing this message?

**Comment by guillemlc** [comment]
Hello. This is from this other comment:

https://github.com/mozilla/geckodriver/issues/659#issuecomment-298244851

`April 30, 2017 - 17:15:32
Django version 1.11, using settings 'superlists.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[30/Apr/2017 17:15:44] "GET / HTTP/1.1" 200 314
Not Found: /favicon.ico
[30/Apr/2017 17:15:44] "GET /favicon.ico HTTP/1.1" 404 2081
**Forbidden (CSRF cookie not set.): /**
[30/Apr/2017 17:15:44] "POST / HTTP/1.1" 403 2857
Performing system checks...`

Without this in the view, I cannot load the page in Firefox. This lets it load.

I believe it to be something new (?) in he given combination:

MacOSX 10.11.6 (15G1421)
geckodriver 0.16.1
Python 3.6.1
FF version 53
selenium 3.4.1
Django 1.11

I know you mention geckodriver  0.15 in the prerequisites, however, as you would see in the issue I link adobe, that gave some other issues (selenium.common.exceptions.WebDriverException: Message: Expected [object Undefined] undefined to be a string). Updating to 0.16.1 makes it work, but then that other issue with CSRF missing token appeared.

So, I wanted to add the workaround if you are able to reproduce.

**Comment by hjwp** [comment]
I'm still not sure when it is you're encountering this problem but I talk about csrf in this chapter? http://www.obeythetestinggoat.com/book/chapter_post_and_database.html

(i confirm you should use the latest geckodriver 16.1 and selenium 3.4.1 btw)

**Comment by hjwp** [comment]
closing this bc i think it was a spurious failure.  feel free to reopen if it repros!

**Pull request closed without merging**
