### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by lookfwd**
Seemed to miss selenium (OS X Yosemite)

### CODE REVIEW

**Comment by hjwp** [comment]
thanks!  I don't think I want to include selenium in the actual requirements.txt, maybe in some sort of test-requirements.txt, but in the meantime i'll update some instructions...

assuming you looked at this because you're coming to the workshop today?  thanks!  did all the tests pass ok?

**Comment by lookfwd** [comment]
Hello,

Yes, coming to the workshop today. :)

Yes, all the tests passed great in about 45 secs. Was fun to watch it
subscribe me to various mailing lists (wasn't it what it was doing?)

**Comment by hjwp** [comment]
haha no, it signs into all your bank accounts and authorizes massive payments to me of course!

(take a look around the site with manage.py runserver if you want to see more of what's going on)

**Comment by lookfwd** [comment]
"If I was about to do this tutorial again... " :) I will think of
something! Good job! :)

**Comment by lookfwd** [comment]
Ok, back to this session. You said that you wanted ideas to make it better
for next time so here are some:

a) good presentation, nice friendly - great
b) django was a problem. people didn't know django and they were learning
too much in too little time. Maybe flask?
c) you don't have time for actual typing. could you be presenting just git
diff at every step - one screen maximum among different steps? Explain the
code/changes, give them 30 sec. to digest and then run... ok - does what's
expected ... next step. What I mean is that PowerPoint works and "let
people sleep" while they learn. Even to demonstrate TDD, there's no need
for actual typing... unless you're using some type of super-hero macros, it
will be great and interesting to watch but it won't easily make a great show
d) Contentwise the curriculum felt great. I think that mocks were of
interest since people see code savings on using them. It was great that
your book is online etc. so one can repeat the steps himself... and of
course buy the book.

Overall, great stuff. Very demanding performance, things went well, people
learned things and left admiring you.

Dimitris

**Pull request closed without merging**
